# Generated by Django 6.0.5 on 2026-09-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveInventory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_number', models.CharField(blank=True, max_length=4000, null=True)),
                ('uom', models.CharField(blank=True, max_length=4000, null=True)),
                ('qty_case', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'active_inventories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('warehouse_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'bin_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=4000, null=True)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('location_1_id', models.BigIntegerField(blank=True, null=True)),
                ('location_2_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=4000, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=4000, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cc_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cycle_counts',
                'ordering': ['-trans_date', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleCountDetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=4000, null=True)),
                ('old_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fst_count_c', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fst_count_pc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fst_count_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fst_count_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sec_count_c', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sec_count_pc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sec_count_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sec_count_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fin_count_c', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fin_count_pc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fin_count_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fin_count_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('inventory_status_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'cycle_count_details',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('item_code', models.CharField(db_column='ItemCode', max_length=13, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=60)),
                ('item_name', models.CharField(db_column='ItemName', max_length=240)),
            ],
            options={
                'db_table': 'InventoryMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'warehouses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CounterAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code_digest', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mobile_counter_accounts',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CounterCountLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle_count_id', models.BigIntegerField(db_index=True)),
                ('cycle_count_code', models.CharField(blank=True, max_length=4000, null=True)),
                ('cycle_count_detail_id', models.BigIntegerField(db_index=True)),
                ('active_inventory_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('location', models.CharField(blank=True, max_length=4000, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=4000, null=True)),
                ('count_stage', models.CharField(default='final', max_length=20)),
                ('actual_cs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_pc', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_logs', to='cycle_counts.counteraccount')),
            ],
            options={
                'db_table': 'mobile_counter_count_logs',
                'ordering': ['-counted_at', '-id'],
                'indexes': [models.Index(fields=['cycle_count_detail_id', '-counted_at'], name='mobile_cc_detail_time_idx')],
            },
        ),
    ]
