# Generated by Django 6.0.5 on 2026-09-07 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_counts', '0002_counteraccount_counter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteraccount',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='counteraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('counter', 'Counter')], default='counter', max_length=20),
        ),
        migrations.AddField(
            model_name='counteraccount',
            name='session_version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='counteraccount',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='counteraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('username__isnull', False)), fields=('username',), name='mobile_account_username_unique'),
        ),
    ]
