# Generated by Django 6.0.5 on 2026-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_counts', '0003_staff_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('counter', 'Counter')], default='counter', max_length=20),
        ),
    ]
