# Generated by Django 6.0.5 on 2026-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_counts', '0008_detail_metadata_from_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercountlog',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countercountlog',
            name='expiry_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countercountlog',
            name='lot_no_from',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='countercountlog',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countercountlog',
            name='production_date_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
