# Generated by Django 6.0.5 on 2026-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_counts', '0009_countercountlog_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercountlog',
            name='expiry_date_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countercountlog',
            name='lot_no_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countercountlog',
            name='production_date_changed',
            field=models.BooleanField(default=False),
        ),
    ]
